# Site Details
title: Pradyun Gedam
blog_title: Deep Thoughts and Nonsense
description: Pradyun Gedam's personal website

email: hi@pradyunsg.me
author: Pradyun Gedam

# Site Configuration
baseurl: ""
url: "https://pradyunsg.me"
date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
sass:
  style: compressed
plugins:
  - jekyll-default-layout
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-redirect-from

# Blog Settings
blog:
  name: Scribbled Notes
  link: /blog/
permalink: blog/:year/:month/:day/:title/
paginate: 7
paginate_path: "/blog/:num/"

# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

titles_from_headings:
  strip_title: true
  collections: true
