# Site settings
title:       Pixyll
email:       your_email@example.com
author:      John Otander
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://pixyll.com"
date_format: "%b %-d, %Y"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Blog Settings
permalink: blog/:year/:month/:day/:title/
paginate: 4
paginate_path: "/blog/:num/"

# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
