baseURL = "http://namannimmo.me/"
title = "Naman Gera"
theme = "PaperMod"

# Infer my posts' dates from filename, like Jekyll
[frontmatter]
date = [":filename", ":default"]

# Use the same URL structure as my Jekyll blog
[permalinks]
blog = "blog/:year/:month/:day/:slug/"

[params]
defaultTheme = "auto"
showReadingTime = true
showPostNavLinks = true

# Shown on the home page
socialIcons = [
  { name = "email", url = "mailto:namangera15@gmail.com" },
  { name = "github", url = "https://github.com/namannimmo10" },
  { name = "twitter", url = "https://twitter.com/namannimmo" },
  { name = "quora", url = "https://www.quora.com/profile/Naman-Gera-11" },
  { name = "stackoverflow", url = "https://stackoverflow.com/users/11750129/namannimmo"},
  { name = "linkedin", url = "https://www.linkedin.com/in/namannimmo/" },
]

# Configure the home page
[params.profileMode]
enabled = true
title = "Hi, I'm Naman."
subtitle = "You can find me in a lot of places on the internet -- I go by the handle namannimmo"

# Site-wide navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "about"
title = "About"
url = "/about/"

[[menu.main]]
weight = 2
identifier = "blog"
name = "blog"
title = "blog"
url = "/blog/"


# Allow HTML in my content pages.
[markup.goldmark.renderer]
unsafe = true
